name: Continous Integration For Ingestion Function App

on: [workflow_dispatch]

jobs:
    checkout:
        runs-on: ubuntu-latest
        outputs:
            commit_sha: ${{ steps.check_out.outputs.sha }}
            branch_name: ${{ steps.check_out.outputs.ref }}
        steps:
            - name: Checkout Source Code
              id: Checkout
              uses: actions/checkout@v4
             
    build:
        runs-on: ubuntu-latest
        needs: checkout
        steps:
            - name: get insights about source code checkout
              run: |
                echo "commit_shs:${{needs.checkout.outputs.commit_sha}}"
                echo "branch_name:${{needs.checkout.outputs.branch_name}}"
              