name: Continous Integration For Ingestion Function App

on: [workflow_dispatch]

jobs:
    checkout:
        runs-on: ubuntu-latest
        outputs:
            commit_sha: ${{ steps.check_out.outputs.commit }}
            branch_name: ${{ steps.check_out.outputs.ref }}
        steps:
            - name: Checkout Source Code
              id: check_out
              uses: actions/checkout@v4

    lint :
        runs-on: ubuntu-latest
        needs: checkout
        steps:
            - name: Setup node environment
              uses: actions/setup-node@v4
              with:
                node-version: "18"
            
            - name: Install Dependencies
              run: npm ci

            - name: Check diretory structure
              run: |
                pwd
                cd ..
                ls -al

             
    # build:
    #     runs-on: ubuntu-latest
    #     needs: checkout
    #     steps:
    #         - name: get insights about source code checkout
    #           run: |
    #             echo "commit_sha:${{needs.checkout.outputs.commit_sha}}"
    #             echo "branch_name:${{needs.checkout.outputs.branch_name}}"
              